### ISSUE TITLE
ModuleNotFoundError: No module named 'openvoice'

### ISSUE THREAD

**Issue by grigio** [myshell-ai/OpenVoice#147]
I tried with your Colab but it also on native linux

```
import os
import torch
from openvoice import se_extractor
from openvoice.api import BaseSpeakerTTS, ToneColorConverter
```

```---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-1-de7f0ac64a9e>](https://localhost:8080/#) in <cell line: 3>()
      1 import os
      2 import torch
----> 3 from openvoice import se_extractor
      4 from openvoice.api import BaseSpeakerTTS, ToneColorConverter

ModuleNotFoundError: No module named 'openvoice'
```

**Comment by withoutbuff** [comment]
+1

**Comment by withoutbuff** [comment]
(openvoice) PS G:\open_voice\OpenVoice> python.exe .\openvoice\openvoice_app.py
Traceback (most recent call last):
  File "G:\open_voice\OpenVoice\openvoice\openvoice_app.py", line 8, in <module>
    from openvoice.api import BaseSpeakerTTS, ToneColorConverter
  File "C:\Users\16159\anaconda3\envs\openvoice\lib\site-packages\openvoice\api.py", line 9, in <module>
    from openvoice.text import text_to_sequence
ModuleNotFoundError: No module named 'openvoice.text'

**Comment by withoutbuff** [comment]
> I tried with your Colab but it also on native linux
> 
> ```
> import os
> import torch
> from openvoice import se_extractor
> from openvoice.api import BaseSpeakerTTS, ToneColorConverter
> ```
> 
> ```
> 
> ModuleNotFoundError                       Traceback (most recent call last)
> 
> [<ipython-input-1-de7f0ac64a9e>](https://localhost:8080/#) in <cell line: 3>()
>       1 import os
>       2 import torch
> ----> 3 from openvoice import se_extractor
>       4 from openvoice.api import BaseSpeakerTTS, ToneColorConverter
> 
> ModuleNotFoundError: No module named 'openvoice'
> ```

git reset --hard 2c8a8e269a8f88c9970a254df70050cacfee0d3f

**Comment by jinxiaotuan** [comment]
+1

**Comment by ntanhfai** [comment]
> (openvoice) PS G:\open_voice\OpenVoice> python.exe .\openvoice\openvoice_app.py Traceback (most recent call last): File "G:\open_voice\OpenVoice\openvoice\openvoice_app.py", line 8, in from openvoice.api import BaseSpeakerTTS, ToneColorConverter File "C:\Users\anaconda3\envs\openvoice\lib\site-packages\openvoice\api.py", line 9, in from openvoice.text import text_to_sequence ModuleNotFoundError: No module named 'openvoice.text'

+1

**Comment by mambari** [comment]
You are just in the wrong folder to execute the code.
Move to OpenVoice
![image](https://github.com/myshell-ai/OpenVoice/assets/10997358/6cffc5a3-a7ee-43d9-8693-a3b7413aaa98)

**Comment by ANK789** [comment]
Move file openvoice_app.py  to \OpenVoice Folder，then run it !

**Comment by ADD-eNavarro** [comment]
I'm trying to run the demo_part1.py, and I'm getting the same message, even when I run it from the same folder where openvoice_app.py is. 
I've created a "test.py" file to run directly on command line with the virtual environment active, but same error pops up.
Any clues?

**Comment by ADD-eNavarro** [comment]
I am having the same issue while being at the right folder. Any advice?

**Comment by ahmedeltaher** [comment]
Is there any solution for this issue yet? I'm not able to run it on my local machine even when I update the latest versions
![Screenshot 2024-10-10 at 23 40 01](https://github.com/user-attachments/assets/b4bc7c34-4e75-4007-8f60-82fd5e37cef9)

**Comment by D3xtor** [comment]
+1

**Comment by NimaDorzh** [comment]
I have the same issue with ModuleNotFoundError: No module named 'openvoice'

**Comment by xtri98** [comment]
The solution is simple dont name OpenVoice/OpenVoice, bruh I took me 4 hrs to figure out

**Comment by garland92** [comment]
Here is solution
https://github.com/myshell-ai/OpenVoice/issues/403#issue-3091897902
