### ISSUE TITLE
Cannot install on Python version 3.11.8; only versions >=3.7,<3.11 are supported.

### ISSUE THREAD

**Issue by Eddy-Powers** [myshell-ai/OpenVoice#164]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yy0htwn4/numba_fa7d338fc5844d07a46d40883585ba6a/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-yy0htwn4/numba_fa7d338fc5844d07a46d40883585ba6a/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.8; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Eddy-Powers** [comment]
In the same virture environment, it can't install different python version. like this How to do ?
thnx

**Comment by donno** [comment]
I tweaked the requirements.txt, to raise the version of numpy similar principal to #156 but I went for latest and this allowed the depedencies to be installed.
```diff
-numpy==1.22.0
+numpy==1.26.4
```

Prior to that change pip wanted to install numba 0.56.4 for me. This was problematic as support for Python 3.11 was added to numba in 0.57.0. The minimum version of numpy required for that version of numba was raised to 1.21 or greater (so 1.22.0) should be newer enough for that..
