### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by mcrey11** [myshell-ai/OpenVoice#222]
C:\Users\Admin\anaconda3\envs\openvoice\lib\site-packages\gradio\components\dropdown.py:93: UserWarning: The `max_choices` parameter is ignored when `multiselect` is False.
  warnings.warn(
Traceback (most recent call last):
  File "C:\OpenVoice-main\openvoice_app.py", line 246, in <module>
    ref_gr = gr.Audio(
  File "C:\Users\Admin\anaconda3\envs\openvoice\lib\site-packages\gradio\component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'info'

**Comment by mcrey11** [comment]
-fix-
pip install --upgrade gradio==3.48.0
