### ISSUE TITLE
I want to run OpenVoiceV2 huggingface demo on my local GPU.

### ISSUE THREAD

**Issue by tar-xzvff** [myshell-ai/OpenVoice#306]
I am running on a local GPU (NVIDIA T4) on a Jupyter notebook with OpenVoiceV2.
How can I run the huggingface demo (with WebUI) on my local GPU?
https://huggingface.co/spaces/myshell-ai/OpenVoiceV2

**Comment by nitinmukesh** [comment]
@dosu

The above code doesn't work as it is incorrect

(openvoice) C:\ai\OpenVoice>python openvoice\openvoice_app2.py
Traceback (most recent call last):
  File "C:\ai\OpenVoice\openvoice\openvoice_app2.py", line 23, in <module>
    en_base_speaker_tts = BaseSpeakerTTS(f'{en_ckpt_base}/config.json', device=device)
  File "c:\ai\openvoice\openvoice\api.py", line 21, in __init__
    hps = utils.get_hparams_from_file(config_path)
  File "c:\ai\openvoice\openvoice\utils.py", line 7, in get_hparams_from_file
    with open(config_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints_v2/base_speakers/EN/config.json'
