### ISSUE TITLE
missing/unexpected keys: [] []

### ISSUE THREAD

**Issue by Datou** [myshell-ai/OpenVoice#37]
after run python -m openvoice_app --share, i got this:

> Loaded checkpoint 'checkpoints/base_speakers/EN/checkpoint.pth'
> missing/unexpected keys: [] []
> Loaded checkpoint 'checkpoints/base_speakers/ZH/checkpoint.pth'
> missing/unexpected keys: [] []
> Loaded checkpoint 'checkpoints/converter/checkpoint.pth'
> missing/unexpected keys: [] []
> F:\OpenVoice\installer_files\env\lib\site-packages\gradio\components\dropdown.py:90: UserWarning: The `max_choices` parameter is ignored when `multiselect` is False.
>   warnings.warn(
> Traceback (most recent call last):
>   File "F:\OpenVoice\installer_files\env\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "F:\OpenVoice\installer_files\env\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "F:\OpenVoice\openvoice_app.py", line 267, in <module>
>     ref_gr = gr.Audio(
>   File "F:\OpenVoice\installer_files\env\lib\site-packages\gradio\component_meta.py", line 157, in wrapper
>     return fn(self, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'info'

**Comment by midpoint** [comment]
me too

**Comment by lzsnolimit** [comment]
Try to run with proxy.

**Comment by davechilds** [comment]
> Gradio with version 3.48.0 works well (the default version on HuggingFace Space).
> 
> Resolve the issue by executing the following command:
> 
> ```
> pip install --upgrade gradio==3.48.0
> ```
> 
> This should resolve the problem without requiring any modifications to the Gradio code in `openvoice_app.py`.
> 
> We have already specified the exact version of Gradio in the requirements file.

I have also encountered the unexpected keys messages - following your post, I did the gradio version install, but the errors are still there - they are exactly the same as the OP example, with each message coming after the checkpoints loading
