### ISSUE TITLE
Windows Install - "ModuleNotFoundError: No module named 'langid'"

### ISSUE THREAD

**Issue by AILova** [myshell-ai/OpenVoice#73]
Install went fine, however, when I run openvoice_app.py it throws the following:

(openvoice) F:\AI_TOOLS\openvoice\OpenVoice>openvoice_app.py
Traceback (most recent call last):
  File "F:\AI_TOOLS\openvoice\OpenVoice\openvoice_app.py", line 6, in <module>
    import langid
ModuleNotFoundError: No module named 'langid'

I tried to fix it by doing pip install langid, and I also did conda install langid for kicks... both completed, but neither solved the problem.  

Any suggestions?  

Thanks!

**Comment by Zengyi-Qin** [comment]
Could you make sure langid is importable in your python env? After pip installing, it should be importable

**Comment by AILova** [comment]
Thanks for responding.  After uninstalling and reinstalling langid via 'pip install langid', it now seems to be importable, however, openvoice_app.py still throws the same error.  See below.  Any addt'l help is much appreciated.  Thanks!

(openvoice) F:\AI_TOOLS\openvoice\OpenVoice>openvoice_app.py
Traceback (most recent call last):
  File "F:\AI_TOOLS\openvoice\OpenVoice\openvoice_app.py", line 6, in <module>
    import langid
ModuleNotFoundError: No module named 'langid'

(openvoice) F:\AI_TOOLS\openvoice\OpenVoice>python
Python 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import langid
>>>
