### ISSUE TITLE
Query: Initiating OpenVoice

### ISSUE THREAD

**Issue by RevancheCBT** [myshell-ai/OpenVoice#74]
Once the installation is complete and the checkpoint downloaded, how is the program opened? 

From screenshots, it appears to have a UI similar to automatic1111, but I don't see an equivalent .bat.

**Comment by AILova** [comment]
I had the same issue... but pretty sure you just run the openvoice_app.py script.  That said, I could be wrong as it's not mentioned explicitly in the documentation anywhere.

**Comment by RevancheCBT** [comment]
That was helpful. 
So, to keep this thread up-to-date for others that might be in a similar pickle following installation, here's the steps that got me to the UI (Win11):

- In the OpenVoice-main directory, open a CMD window from the File Explorer address bar.
- add after the OpenVoice-main> prompt: `python openvoice_app.py`
- wait for it to run, until you see To create a public link, set `share=True` in `launch()`."
- Then either click on the http link on the line above it or direct your browser to `http://127.0.0.1:7860`

Right now I'm getting failures that prevent me from actually running it, but...progress!

**Comment by Me-Phew** [comment]
The next step would be to ensure you have FFmpeg along with ffprobe installed and added to PATH (that's the most likely reason for the failures)

**Comment by AiDreamerOoO** [comment]
I tried to start openVoice and these problems occurred，Does anyone know why? Thanks

 C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loaded checkpoint 'checkpoints/base_speakers/EN/checkpoint.pth'
missing/unexpected keys: [] []
Loaded checkpoint 'checkpoints/base_speakers/ZH/checkpoint.pth'
missing/unexpected keys: [] []
Loaded checkpoint 'checkpoints/converter/checkpoint.pth'
missing/unexpected keys: [] []
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components\dropdown.py:90: UserWarning: The `max_choices` parameter is ignored when `multiselect` is False.
  warnings.warn(
Traceback (most recent call last):
  File "E:\openVoice\OpenVoice-main\openvoice_app.py", line 246, in <module>
    ref_gr = gr.Audio(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\component_meta.py", line 157, in wrapper  
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'info'

**Comment by AiDreamerOoO** [comment]
> 我尝试启动 openVoice 并出现这些问题，有人知道为什么吗？谢谢
> 
> C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm 已被弃用，转而使用 torch .nn.utils.parametrizations.weight_norm。 warnings.warn("torch.nn.utils.weight_norm 已弃用，转而使用 torch.nn.utils.parametrizations.weight_norm。") 已加载检查点 'checkpoints/base_speakers/EN/checkpoint.pth' 缺少/意外的键：[] [ ] 已加载检查点“checkpoints/base_speakers/ZH/checkpoint.pth” 缺少/意外密钥：[] [] 已加载检查点“checkpoints/converter/checkpoint.pth” 缺少/意外密钥：[] [] C:\Users\Administrator\ AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components\dropdown.py:90: UserWarning:`max_choices`当为 False 时，该参数将被忽略`multiselect`。 warnings.warn( Traceback (最近一次调用最后一次): File "E:\openVoice\OpenVoice-main\openvoice_app.py", line 246, in ref_gr = gr.Audio( File "C:\Users\Administrator\AppData\Local **\** Programs\Python\Python310\lib\site-packages\gradio\component_meta.py”，第 157 行，在包装器中 返回 fn(self, **kwargs) TypeError: Audio.init () 得到了意外的关键字参数 'info'****

问题解决了 降低gradio版本 gradio==3.48.0

**Comment by giperion85** [comment]
> The next step would be to ensure you have FFmpeg along with ffprobe installed and added to PATH (that's the most likely reason for the failures)

Please tell me how to check it and do it in Ubuntu?

**Comment by Me-Phew** [comment]
> > The next step would be to ensure you have FFmpeg along with ffprobe installed and added to PATH (that's the most likely reason for the failures)
> 
> Please tell me how to check it and do it in Ubuntu?

Assumming you've installed it to the bin directory it already is in your path.

You can check it by typing `ffmpeg -version` in your terminal. It should output some info about the installed version. 
If it says something among the lines of  `Command 'ffmpeg' not found` instead then it isn't added.

In that case you would need to add this line to your ~/.bashrc
`export PATH=$PATH:<path to ffmpeg dir>`
